- name: Include OS-specific tasks for supported OS families
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}_install.yml"
  when: ansible_os_family in vscode_supported_os_families

- name: Include OS-specific tasks for supported OS distributions
  ansible.builtin.include_tasks: "{{ ansible_distribution | lower }}_install.yml"
  when: ansible_distribution in vscode_supported_os_distributions
