- name: Converge
  hosts: all
  remote_user: test-user

  tasks:
    - name: Test Role | Install
      ansible.builtin.include_role:
        name: vscode
        tasks_from: install
  post_tasks:
    - name: Verify installation
      ansible.builtin.command: code -v
      register: vscode_status
      failed_when: vscode_status.rc != 0
      changed_when: false
