vscode_app_name: code
vscode_app_state: present
vscode_repo_state: present

# Extensions
vscode_extensions:
  - ms-vscode-remote.remote-containers
  - ms-azuretools.vscode-docker

# For Redhat Family
vscode_rh_gpg_key: https://packages.microsoft.com/keys/microsoft.asc
vscode_rh_repo_name: code
vscode_rh_repo_description: Visual Studio Code
vscode_rh_repo_url: https://packages.microsoft.com/yumrepos/vscode
vscode_rh_repo_filename: vscode
vscode_rh_repo_gpgcheck: true
vscode_rh_repo_enabled: true
