- name: Setup Workstations
  hosts: private
  tasks:
    - name: Install VS-Code
      ansible.builtin.include_role:
        name: vscode
        tasks_from: install
    - name: Configure VS-Code
      ansible.builtin.include_role:
        name: vscode
        tasks_from: configure
