# kics-scan disable=555ab8f9-2001-455e-a077-f2d0f41e2fb9
name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Run ansible-lint
        uses: ansible/ansible-lint@v24.12.2

  security-scan:
    name: Kics Security Scan
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

      - name: Run kics Scan
        uses: checkmarx/kics-github-action@v2.1.3
        with:
          path: "./"
          fail_on: high,medium

  unit-test:
    name: Unit Test Roles
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        distro:
          - fedora:38
          - fedora:39

    steps:
      - uses: actions/checkout@v3

      - name: Run Unit Tests
        uses: devcontainers/ci@v0.3
        with:
          runCmd: pytest -rP
          env: |
            MOLECULE_DISTRO=${{ matrix.distro }}
            MOLECULE_NO_LOG=false
